[project]
name = "interactive_plot"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "", email = "aj9310@mci4me.at"},
]
dependencies = ["matplotlib>=3.10.9", "pandas>=3.0.3", "streamlit>=1.57.0", "numpy>=2.4.6"]
requires-python = "==3.14.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
